// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/google/uuid"
)

type Comment struct {
	CommentID uuid.UUID
	Comment   string
	PostID    uuid.UUID
	Username  string
}

type Post struct {
	PostID   uuid.UUID
	Post     string
	Username string
}

type User struct {
	Username string
	Hash     string
}
